### ISSUE TITLE
Crashed while going below y 0

### ISSUE THREAD

**Issue by Raumis** [BatHeart/batty-ui-forge#1]
Forge: 13.20.0.2252
battys_coordinates_plus{1.11.2_001}

I created a void world set to creative and when I went below the spawn platform the game crashed.
Crash log:
https://pastebin.com/uRSatws3

**Comment by BatHeart** [comment]
Raumis
Thank you for reporting this bug. It is quite obscure, and I would not expect it to affect many people, but I will address it in the next release.
It is caused by having the Light Level showing in the Info Panel of Batty's Mod (selected by numpad-6). If this is not visible (e.g. you show Moon phase, FPS or nothing) then the error does not occur.
(So, to get back to normal, open another world, select a different Info display via numpad-6, then go into the void world and there should be no crash)
Thanks again.
BatHeart

**Comment by BatHeart** [comment]
Raumis
I have just uploaded battys_coordinates_plus (1.11.2_002) which corrects this issue.

BatHeart
